### ISSUE TITLE
Setup CD for Cloud Run Service

### ISSUE THREAD

**Issue by yuki0920** [yuki0920/company-ranking#829]
Add `gcloud run deploy` command like this in CD to deploy cloud run service with latest image.

```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$SERVICE_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$SERVICE_NAME:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$SERVICE_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$SERVICE_NAME:$COMMIT_SHA'
  - '--region'
  - '$REGION'
```
